"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _task_list from './task-list.bones.json'

registerBones({
  "task-list": _task_list,
})
