/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router when you run `pnpm dev`.
// DO NOT edit this file manually — it will be overwritten.

import { Route as rootRoute } from './app/__root'
import { Route as IndexRoute } from './app/index'
import { Route as TasksRoute } from './app/tasks'

const IndexRouteWithPath = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TasksRouteWithPath = TasksRoute.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren({
  IndexRouteWithPath,
  TasksRouteWithPath,
})
